// <auto-generated />
using System;
using LesegaisParser.Common.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LesegaisParser.Common.Migrations
{
    [DbContext(typeof(LesegaisContext))]
    partial class LesegaisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("LesegaisParser.Common.Model.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuyerInn")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DealDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DealNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerInn")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Typename")
                        .HasColumnType("TEXT");

                    b.Property<double>("WoodVolumeBuyer")
                        .HasColumnType("REAL");

                    b.Property<double>("WoodVolumeSeller")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Deals");
                });
#pragma warning restore 612, 618
        }
    }
}
